name: CSS Linting

on: [push, pull_request]

jobs:
    css-lint:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: RPIHousingPictures
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: Cache Node Modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                       ${{ runner.os }}-cache-node-modules-
            - run: npm install
            - name: Run stylelint
              run: npm run css-stylelint
